//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace P1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.User = new HashSet<UserInfo>();
            this.Action = new HashSet<ActionInfo>();
        }
    
        public System.Guid RoleID { get; set; }
        public string RoleName { get; set; }
        public string RoleType { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> DeleteMark { get; set; }
    
        public virtual ICollection<UserInfo> User { get; set; }
        public virtual ICollection<ActionInfo> Action { get; set; }
    }
}
