//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace P1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Role = new HashSet<Role>();
            this.Action = new HashSet<ActionInfo>();
        }
    
        public System.Guid UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public System.DateTime ModifyTime { get; set; }
        public int DeleteMark { get; set; }
        public Nullable<System.Guid> CreateByID { get; set; }
        public string CreateByName { get; set; }
    
        public virtual ICollection<Role> Role { get; set; }
        public virtual ICollection<ActionInfo> Action { get; set; }
    }
}
